"MANIPULAÇÃO DE ARQUIVOS"


"CRIAR, COPIAR, MOVER E REMOVER ARQUIVOS"

"CRIANDO E REMOVENDO DIRECTÓRIOS"

"MANIPULAÇÃO RECURSIVA DE ARQUIVOS E DIRECTÓRIOS"

"GLOBBING DE ARQUIVOS E CARACTERES CURINGAS"